app = 'serverdo-cold-sunset-556'
primary_region = 'qro'

[build]

[env]
  DATABASE_URL = "postgresql://troncodur0:85t1ZqMqZWYu1zx6vP1wWA@ericks-portafolio-10350.6wr.aws-us-west-2.cockroachlabs.cloud:26257/sample?sslmode=verify-full"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
