// types/stopWords.ts
const STOP_WORDS: Set<string> = new Set([
  "a", "about", "above", "after", "again", "against", "al", "algún", "alguna",
  "algunas", "alguno", "algunos", "all", "algo", "am", "ambos", "an", "and",
  "ante", "antes", "any", "aquel", "aquella", "aquellas", "aquello", "aquellos",
  "aquí", "arriba", "are", "aren't", "arriba", "as", "at", "atrás", "bajo",
  "bastante", "be", "because", "been", "before", "being", "below", "between",
  "bien", "both", "but", "bajo", "by", "cada", "cierta", "ciertas", "cierto",
  "ciertos", "can't", "cannot", "como", "con", "contra", "could", "couldn't",
  "cual", "cuales", "cualquier", "cualquiera", "cualquieras", "cuán", "cuando",
  "cuanta", "cuantas", "cuanto", "cuantos", "de", "del", "did", "didn't", "do",
  "does", "doesn't", "doing", "don't", "demasiada", "demasiadas", "demasiado",
  "demasiados", "dentro", "desde", "donde", "down", "dos", "during", "each",
  "e", "el", "él", "ella", "ellas", "ello", "ellos", "en", "encima", "entonces",
  "entre", "era", "erais", "eran", "eras", "eres", "es", "esa", "esas", "ese",
  "eso", "esos", "esta", "está", "estaba", "estabais", "estaban", "estabas",
  "estad", "estada", "estadas", "estado", "estados", "estamos", "estando",
  "estar", "estaremos", "estará", "estarán", "estarás", "estaré", "estaréis",
  "estaría", "estaríais", "estaríamos", "estarían", "estarías", "estas", "este",
  "estemos", "esto", "estos", "estoy", "estuve", "estuviera", "estuvierais",
  "estuvieran", "estuvieras", "estuvieron", "estuviese", "estuvieseis",
  "estuviesen", "estuvieses", "estuvimos", "estuviste", "estuvisteis",
  "estuviéramos", "estuviésemos", "estuvo", "está", "estábamos", "estáis",
  "están", "estás", "esté", "estéis", "estén", "estés", "excepto", "few", "for",
  "from", "further", "fue", "fuera", "fuerais", "fueran", "fueras", "fueron",
  "fuese", "fueseis", "fuesen", "fueses", "fui", "fuimos", "fuiste", "fuisteis",
  "fuéramos", "fuésemos", "ha", "habéis", "había", "habíais", "habíamos",
  "habían", "habías", "han", "has", "hasta", "hay", "haya", "hayáis", "hayamos",
  "hayan", "hayas", "he", "hemos", "hube", "hubiera", "hubierais", "hubieran",
  "hubieras", "hubieron", "hubiese", "hubieseis", "hubiesen", "hubieses",
  "hubimos", "hubiste", "hubisteis", "hubiéramos", "hubiésemos", "hubo", "la",
  "las", "le", "les", "lo", "los", "had", "hadn't", "has", "hasn't", "have",
  "haven't", "having", "he", "he'd", "he'll", "he's", "her", "here", "here's",
  "hers", "herself", "him", "himself", "his", "how", "how's", "i", "i'd",
  "i'll", "i'm", "i've", "if", "in", "into", "is", "isn't", "it", "it's", "its",
  "itself", "let's", "me", "mi", "mis", "más", "mí", "mía", "mías", "mío",
  "míos", "mucha", "muchas", "mucho", "muchos", "muy", "more", "most",
  "mustn't", "my", "myself", "nada", "ni", "no", "nor", "not", "nos",
  "nosotras", "nosotros", "nuestra", "nuestras", "nuestro", "nuestros", "of",
  "off", "on", "once", "only", "o", "os", "otra", "otras", "otro", "otros",
  "our", "ours", "ourselves", "out", "over", "own", "para", "pero", "poca",
  "pocas", "poco", "pocos", "por", "porque", "primero", "puede", "pueden",
  "puedo", "pues", "que", "quién", "quiénes", "qué", "quien", "quienes",
  "se", "sea", "seamos", "sean", "seas", "seremos", "será", "serán", "serás",
  "seré", "seréis", "sería", "seríais", "seríamos", "serían", "serías", "seáis",
  "si", "sido", "siendo", "sin", "sobre", "so", "sois", "some", "somos", "son",
  "soy", "su", "sus", "suya", "suyas", "suyo", "suyos", "sí", "también",
  "tampoco", "tan", "tanto", "te", "tendremos", "tendrá", "tendrán", "tendrás",
  "tendré", "tendréis", "tendría", "tendríais", "tendríamos", "tendrían",
  "tendrías", "tened", "tenemos", "tenga", "tengamos", "tengan", "tengas",
  "tengo", "tengáis", "tenía", "teníais", "teníamos", "tenían", "tenías", "ti",
  "tiene", "tienen", "tienes", "todo", "todos", "tu", "tus", "tuve", "tuviera",
  "tuvierais", "tuvieran", "tuvieras", "tuvieron", "tuviese", "tuvieseis",
  "tuviesen", "tuvieses", "tuvimos", "tuviste", "tuvisteis", "tuviéramos",
  "tuviésemos", "tuvo", "tuya", "tuyas", "tuyo", "tuyos", "tú", "un", "una",
  "uno", "unos", "usted", "ustedes", "varias", "varios", "vosotras", "vosotros",
  "vuestra", "vuestras", "vuestro", "vuestros", "was", "wasn't", "we", "we'd",
  "we'll", "we're", "we've", "were", "weren't", "what", "what's", "when",
  "when's", "where", "where's", "which", "while", "who", "who's", "whom", "why",
  "why's", "with", "won't", "would", "wouldn't", "y", "ya", "yo", "you", "you'd",
  "you'll", "you're", "you've", "your", "yours", "yourself", "yourselves",
  "él", "éramos"
]);

export default STOP_WORDS;

